<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ICWS-1162" name="TC_CFS_07 : To verify user start operation for selected job." tests="7" failures="1" timestamp="9 Mar 2017 04:32:45 GMT" time="44.825" errors="0">
  <testcase name="requestByBOLFlow" time="34.638" classname="com.cfs.index.ServiceRequestIndex">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.cfs.index.ServiceRequestIndex.requestByBOLFlow(ServiceRequestIndex.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- requestByBOLFlow -->
  <testcase name="planPostpaidRequest" time="0.0" classname="com.cfs.index.ServiceRequestIndex">
    <skipped/>
  </testcase> <!-- planPostpaidRequest -->
  <testcase name="approvePostpaidRequest" time="0.0" classname="com.cfs.index.ServiceRequestIndex">
    <skipped/>
  </testcase> <!-- approvePostpaidRequest -->
  <testcase name="viewCreatedJob" time="0.0" classname="com.cfs.index.JobIndex">
    <skipped/>
  </testcase> <!-- viewCreatedJob -->
  <testcase name="planCreatedJob" time="0.0" classname="com.cfs.index.JobIndex">
    <skipped/>
  </testcase> <!-- planCreatedJob -->
  <testcase name="confirmContainerArrival" time="0.0" classname="com.cfs.index.JobIndex">
    <skipped/>
  </testcase> <!-- confirmContainerArrival -->
  <testcase name="startJobwithCutSeal" time="0.0" classname="com.cfs.index.JobIndex">
    <skipped/>
  </testcase> <!-- startJobwithCutSeal -->
</testsuite> <!-- TC_CFS_07 : To verify user start operation for selected job. -->
